---
engines:
  eslint-9:
    enabled: true
exclude_paths:
  - '**/node_modules/**'
  - '**/dist/**'
  - '**/build/**'
  - '**/coverage/**'
  - '**/__tests__/**'
  - '**/*.test.ts'
  - '**/*.test.js'
  - '**/*.mock.ts'
  - '**/*.spec.js'
  - '**/*.config.js'
  - '**/*.config.mjs'
  - '**/*.config.ts'
  - 'apps/api/src/**/migrations/**'
  - 'apps/api/src/data/scripts/**'
  - 'apps/web/e2e/**'
  - 'apps/web/src/tests/**'
