# Identity
sonar.projectKey=smela
sonar.projectName=smela

# Monorepo modules
sonar.modules=api,web

api.sonar.projectName=@smela/api
api.sonar.projectBaseDir=apps/api
api.sonar.sources=src
api.sonar.tests=src
api.sonar.test.inclusions=**/*.test.ts
api.sonar.coverage.exclusions=src/**/*.test.ts
api.sonar.javascript.lcov.reportPaths=coverage/lcov.info

web.sonar.projectName=@smela/web
web.sonar.projectBaseDir=apps/web
web.sonar.sources=src
web.sonar.tests=src
web.sonar.test.inclusions=**/__tests__/**,**/*.spec.js,**/*.test.js
web.sonar.coverage.exclusions=src/**/*.stories.*,src/**/*.test.*,src/**/*.spec.*,src/tests/**
web.sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusions
sonar.exclusions=\
  apps/api/src/data/migrations/**/*.sql,\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  **/*.stories.*

sonar.coverage.exclusions=\
  apps/api/src/data/scripts/**,\
  apps/api/src/emails/**,\
  apps/web/src/tests/**
