# Identity
sonar.projectKey=SlavaMelanko_smela
sonar.projectName=smela
sonar.organization=smelanko

# Sources and tests
sonar.sources=apps/api/src,apps/web/src
sonar.tests=apps/api/src,apps/web/src

sonar.test.inclusions=\
  apps/api/**/*.test.ts,\
  apps/web/**/__tests__/**,\
  apps/web/**/*.test.js,\
  apps/web/**/*.spec.js

# Exclusions
sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  **/*.stories.*,\
  apps/api/src/data/migrations/**/*.sql,\
  apps/api/**/*.test.ts,\
  apps/web/**/__tests__/**,\
  apps/web/**/*.test.js,\
  apps/web/**/*.spec.js

sonar.coverage.exclusions=**/*
