export { DashboardPage } from './Dashboard'
export { EmailSenderProfilePage, SocialLinkPage, SystemPage } from './System'
export { TeamPage } from './Team'
export { TeamsPage } from './Teams'
export { UserPage } from './User'
export { UsersPage } from './Users'
