name: Coverage

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
    secrets:
      CODECOV_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.app_name }}-coverage-${{ github.sha }}
          path: apps/${{ inputs.app_name }}/coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: apps/${{ inputs.app_name }}/coverage/lcov.info
          flags: ${{ inputs.app_name }}
          fail_ci_if_error: true

      - name: Upload coverage to SonarCloud
        uses: sonarsource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
